# SITE CONFIGURATION
remote_theme: rohanchandra/type-theme

defaultlang: "en"

# SEO CONFIG
title: VubbiScript
description: VubbiScript is a plugin for Unity3D aimed at kids which allows you to do visual programming in Unity3D.
logo: /assets/img/Logo.png
webmaster_verifications:
  google: 27ypTs7dWpOPW8VwESOh5thv8VVh1OcQwpN07rALTWQ
lang: en

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  title: VubbiScript
  subtitle: Met blokjes programmeren in Unity3D...
  avatar: assets/img/Logo/logo.svg
  avataralt: "VubbiScript"
  favicon: assets/favicon.ico # without / at the beginning!
  gravatar: # Email MD5 hash
  description: "VubbiScript - Met blokjes programmeren in Unity3D..." # used by search engines
   
  # Icons
  email_address: auto-replace # e-mailaddress will be auto replaced by javascript
  github: "VubbiScript"
  
  # Localization strings
  str_follow_on: "Follow on"
  str_email: "Email"

  # Scripts / Features 
  google_analytics: GTM-56V3N2P
  google_analytics_track_domain: VubbiScript.github.io
  google_analytics_dev_cookie: VUBBISCRIPTGITHUBIODEVCOOKIE=IAMDEV
  google_analytics_dev_debug_tracking: false
  disqus_shortname:

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PORTFOLIO
collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-remote-theme, jekyll-redirect-from, jekyll-github-metadata]

# Exclude from processing.
exclude: ["Gemfile", "Gemfile.lock", "*.gem", "LICENSE", "README.md", "WIP"]

